# https://symfony.com/doc/current/service_container.html
parameters:
    app.timezone: UTC
    app.locale: es

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
